---
title: "Análise Estatística do casos de cancer antes e depois do acidente de Chernobyl"
author: "Huggo Parcelly - Victor Paiva"
date: "2022-11-21"
output: pdf_document
editor_options: 
  markdown: 
    wrap: 72
---

## Descrição do problema

O acidente com a usina nuclear de Chernobyl aconteceu no dia 26 de abril
de 1986, no qual houve uma explosão em um reator, lançando material
radioativo na atmosfera. A radiação logo se espalhou pelo o mundo,
contudo as consequências foram mais profundas sobretudo para três
países: Ucrânia, Bielorrússia e Rússia.

Uma consequência grave do acidente foi o aumento dos casos de cancer,
que será o objeto de estudo desse relatório. Para tal, utilizou-se um
banco de dados que foi retirado a partir de um estudo com as populações
das cidades de Gomel, Mogilev e Belarus, que são próximas ao acidente.
As populações estudadas foram divididas em dois grupos, antes e depois
do aciente de Chernobyl, nos anos de 1985 e 1986.

Para fins de estudos desse relatório, levantou-se a problemática para
comparar as médias dos casos de cancer e classificar qual(is) o(s)
tipo(s) de cancer com maior número de casos após o acidente.

## População associada

Homens e mulheres das cidades de Gomel, Mogilev e Belarus

## Variáveis e tipos de interesse para pesquisa

A variável em estudo é a quantidade de casos de cancer, na população das
três cidades e é do tipo quantitiva discreta.

## Objetivos do estudo

### Objetivos gerais

Comparar as médias dos casos de cancer na população das três cidades,
analisando os anos 1985 e 1986.

### Objetivos específicos

Realizou-se uma comparação das médias dos casos de cancer, por 100.000
pessoas, das cidades de Gomel, Mogilev e Belarus, nos anos de 1985 e
1986.E o objetivo é verificar em quanto foi o aumento do número de
casos.

### Hipóteses (caso tenha)

## Coleta de amostra

Os dados utilizados nesse relatório foram coletados a partir de um
estudo feito com a população das cidades de Gomel, Mogilev e Belarus,
que foram produndamente afetadas pela explosão de Chernobyl.

## Parâmetro, Estatística e Estimativa

Parâmetros: Médias dos casos antes e depois da explosão. Estimativa:
Estima-se que as médias dos casos de cancer aumentou.

## Análise Exploratória de Dados (EDA)

    if(!require(magrittr)) install.packages("magrittr") 
    library(magrittr) 

    if(!require(dplyr)) install.packages("dplyr") 
    library(dplyr) 

    if(!require(ggplot2)) install.packages("ggplot2") 
    library(ggplot2) 

    if(!require(readr)) install.packages("readr") 
    library(readr)

        dados <- read_csv("cancer_before_and_after_Chernobyl_Belarus.csv")
        
        ## Dados antes do acidente
        before = subset(dados, dados$year == 1985)
        
        ## Dados depois do acidente
        after = subset(dados, dados$year == 1986)

        total_rate_before = sum(before$cases) 
        total_rate_after = sum(after$cases)

        total_rate <- c(total_rate_before, total_rate_after) 

        years <- c(1985,1986)

        perc_higher <- total_rate_after/total_rate_before * 100

        df_total <- data.frame(years, total_rate)

## Grafico de barras para visualizar a relação de casos de cancer com o acidente nuclear de Chernobyl.

        df_total %>% ggplot() + geom_col(aes(x=years, y=total_rate)) + ggtitle("Casos de Cancer em Chernobyl comparando antes e depois do acidente nuclear em Chernobyl no ano 1986") + ylab("Casos de cancer") + expand_limits(y=0) + xlab("1985 vs 1986") + theme(axis.text.x=element_blank())

## Histograma separado por ano.

    ggplot(data = dados, mapping = aes(x = cases)) +
    geom_histogram(color = "white") + facet_wrap(~ year, ncol = 1) +
    labs(x="Casos de cancer")

        dados1 <- transform( dados, acidente= ifelse(year==1985, "before", "after"))

        dados1 %>% ggplot(aes(x = cases)) + geom_density(aes(fill = acidente),
        alpha = 0.5 ) + labs(x="Casos de cancer", y="Densidade")
        
        ## Gráfico dos casos de cancer nas três cidades, antes e depois do acidente
        dados %>% ggplot() + geom_col(aes(year,cases, fill=cancer_type), alpha=0.7) + facet_grid(.~location) + scale_x_continuous(breaks = c(1985, 1986), labels = c("before", "after")) + ggtitle("Casos de cancer em diferentes cidades nantes e depois do acidente nuclear de Chernobyl")

        df_total

        x1 <- dados1$cases[dados1$acidente == "before"]
        x2 <- dados1$cases[dados1$acidente == "after"]

        par(mfrow = c(2,1), mar = rep(2.5, 4))

        hist(x1, prob=TRUE, main = "1985") 
        lines(density(x1))

        hist(x2, prob=TRUE, main = "1986", xlab = "Casos de cancer")
        lines(density(x2))
        

## Inferências estatísticas

Foram realizadas 84 observações, sendo 42 no ano de 1985 e 42 no ano de
1985, período antes e depois do acidente de Chernobyl. Para esses dados
foram observados as quantidades de casos, para 7 tipos de câncer, por
100.000 habitantes, homens e mulheres, em mesma proporção. Os tipos de
câncer observados foram colon, rim, pele, pulmão, pancreas, reto e
tireoide.

Vamos verificar a média de todos os casos de câncer nos dois anos,
referentes a antes e depois do acidente.


    mean_before = mean(before$cases)
    mean_after = mean(after$cases)

Aparentemente houve um aumento de casos de cancer após o acidente na
usina nuclear de Chernoby, vamos provar essa hipótese.

Usaremos o teste de hipóteses para comprovar se realmente houve um
aumento dos casos de cancer em todas as cidades ou foi apenas uma
coincidência da amostra coletada.

H0 como sendo a hipótese de que não houve um aumento do número de casos
de cancer H1 como sendo a hipótese de que houve um aumento do número de
casos de cancer

Tomando o nível de significancia como 0.001

Vamos rejeitar H0, que é a a hipótese de que não houve um aumento nos
casos de cancer.
